#!/usr/bin/env python3
import json

# Create properly escaped training data with error resolution examples
data = [
    "User: List all files in the current directory. Assistant: <tool_call> name = shell args = ls -la </tool_call> <tool_result> total 128\ndrwxr-xr-x  5 user user  4096 Feb  8 14:00 .\n-rw-r--r--  1 user user  2048 Feb  8 14:00 README.md\n-rw-r--r--  1 user user  8192 Feb  8 13:30 Cargo.toml </tool_result> Here are the files in the current directory: README.md, Cargo.toml, src/, data/, and .gitignore. </s>",
    "User: Check git status. Assistant: <tool_call> name = shell args = git status </tool_call> <tool_result> On branch main\nYour branch is up to date with 'origin/main'.\n\nChanges not staged for commit:\n modified: src/main.rs\n modified: Cargo.toml\n\nUntracked files:\n training.log </tool_result> You have uncommitted changes in src/main.rs and Cargo.toml, plus an untracked training.log file. </s>",
    "User: Build the project. Assistant: <tool_call> name = shell args = cargo build </tool_call> <tool_result> error: could not find `Cargo.toml` in `/home/user` or any parent directory\n </tool_result> <tool_call> name = shell args = pwd </tool_call> <tool_result> /home/user </tool_result> <tool_call> name = shell args = cd /home/user/projects/rustgpt && cargo build </tool_call> <tool_result> Compiling llm v0.1.0 (/home/user/projects/rustgpt)\n Finished dev [unoptimized + debuginfo] target(s) in 12.45s </tool_result> I had to navigate to the correct directory first. Build completed successfully. </s>",
    "User: Install the missing dependency. Assistant: <tool_call> name = shell args = pip install numpy </tool_call> <tool_result> ERROR: Could not find an activated virtualenv (required).\n </tool_result> <tool_call> name = shell args = python3 -m pip install numpy --user </tool_call> <tool_result> Collecting numpy\n  Downloading numpy-1.24.0-cp310-cp310-manylinux_2_17_x86_64.whl (17.3 MB)\n     ||████████████████████████████████| 17.3 MB 12.3 MB/s \nInstalling collected packages: numpy\nSuccessfully installed numpy-1.24.0 </tool_result> The virtual environment requirement blocked the install, so I used --user flag instead. NumPy installed successfully. </s>",
    "User: Run the training script. Assistant: <tool_call> name = shell args = ./train.sh </tool_call> <tool_result> bash: ./train.sh: Permission denied\n </tool_result> <tool_call> name = shell args = chmod +x train.sh && ./train.sh </tool_call> <tool_result> Starting training...\nEpoch 1/100: loss=2.3456\nEpoch 2/100: loss=2.1234\n... </tool_result> The script wasn't executable. Fixed permissions with chmod and started training successfully. </s>",
    "User: Push my changes to git. Assistant: <tool_call> name = shell args = git push </tool_result> <tool_result> To github.com:user/rustgpt.git\n ! [rejected]        main -> main (fetch first)\nerror: failed to push some refs to 'github.com:user/rustgpt.git'\nhint: Updates were rejected because the remote contains work that you do\nhint: not have locally. </tool_result> <tool_call> name = shell args = git pull --rebase </tool_call> <tool_result> remote: Enumerating objects: 15, done.\nFrom github.com:user/rustgpt\n   abc1234..def5678  main       -> origin/main\nSuccessfully rebased and updated refs/heads/main. </tool_result> <tool_call> name = shell args = git push </tool_call> <tool_result> Enumerating objects: 23, done.\nTo github.com:user/rustgpt.git\n   def5678..ghi9012  main -> main </tool_result> There were remote changes I needed to pull first. After rebasing, the push completed successfully. </s>",
    "User: Connect to the database. Assistant: <tool_call> name = shell args = psql -U postgres -d mydb </tool_call> <tool_result> psql: error: connection to server on socket \"/var/run/postgresql/.s.PGSQL.5432\" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n </tool_result> <tool_call> name = shell args = sudo systemctl start postgresql </tool_call> <tool_result> Starting postgresql (via systemctl): postgresql.service. </tool_result> <tool_call> name = shell args = psql -U postgres -d mydb </tool_call> <tool_result> psql (14.5)\nType \"help\" for help.\n\nmydb=# </tool_result> The PostgreSQL service wasn't running. Started it and connected successfully. </s>",
    "User: Compile with optimizations. Assistant: <tool_call> name = shell args = rustc -O main.rs </tool_call> <tool_result> error: linking with `cc` failed: exit code: 1\n  |\n  = note: /usr/bin/ld: cannot find -lsqlite3\n          collect2: error: ld returned 1 exit status\n </tool_result> <tool_call> name = shell args = sudo apt-get install libsqlite3-dev </tool_call> <tool_result> Reading package lists... Done\nGet:1 http://archive.ubuntu.com/ubuntu jammy/main libsqlite3-dev amd64 3.37.2-2 [846 kB]\nUnpacking libsqlite3-dev (3.37.2-2) ...\nSetting up libsqlite3-dev (3.37.2-2) ... </tool_result> <tool_call> name = shell args = rustc -O main.rs </tool_call> <tool_result> </tool_result> Missing SQLite development library. Installed it and compilation succeeded. </s>",
    "User: Update the package list. Assistant: <tool_call> name = shell args = apt update </tool_call> <tool_result> Reading package lists... Done\nE: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)\nE: Unable to lock directory /var/lib/apt/lists/ </tool_result> <tool_call> name = shell args = sudo apt update </tool_call> <tool_result> Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease\nGet:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]\nFetched 255 kB in 2s (112 kB/s)\nReading package lists... Done\n98 packages can be upgraded. </tool_result> Needed sudo permissions. Package list updated - 98 packages can be upgraded. </s>",
    "User: Merge the pull request branch. Assistant: <tool_call> name = shell args = git merge feature-branch </tool_call> <tool_result> Auto-merging src/main.rs\nCONFLICT (content): Merge conflict in src/main.rs\nAutomatic merge failed; fix conflicts and then commit the result.\n </tool_result> <tool_call> name = shell args = grep -n '<<<<<<<|=======|>>>>>>>' src/main.rs </tool_call> <tool_result> 45:<<<<<<< HEAD\n46:    let model = load_model();\n47:=======\n48:    let model = Model::new();\n49:>>>>>>> feature-branch </tool_result> There's a merge conflict in src/main.rs. Lines 45-49 show the conflict between HEAD (load_model) and feature-branch (Model::new). Resolve by choosing one approach or combining them. </s>",
    "User: Check disk space. Assistant: <tool_call> name = shell args = df -h </tool_call> <tool_result> Filesystem      Size  Used Avail Use% Mounted on\n/dev/sda3       496G  490G  5.8G  99% / </tool_result> <tool_call> name = shell args = du -sh /var/log/* | sort -h | tail -3 </tool_call> <tool_result> 123M\t/var/log/syslog\n2.1G\t/var/log/kern.log\n8.5G\t/var/log/old_logs </tool_result> Disk is 99% full! The /var/log/old_logs directory is using 8.5GB. You should clean up old logs to free space. </s>",
    "User: Debug the failing test. Assistant: <tool_call> name = shell args = cargo test test_attention -- --nocapture </tool_call> <tool_result> running 1 test\ntest tests::test_attention ... FAILED\nfailures:\nthread 'tests::test_attention' panicked at 'assertion failed: `(left == right)`\n  left: `[0.1, 0.2, 0.3]`,\n right: `[0.1, 0.2, 0.4]`', src/tests.rs:45:9 </tool_result> The test failed at line 45 in src/tests.rs - expected [0.1, 0.2, 0.4] but got [0.1, 0.2, 0.3]. The third value differs by 0.1. Check the attention computation logic. </s>",
    "User: Check why cargo is slow. Assistant: <tool_call> name = shell args = cargo build --release --timings </tool_call> <tool_result> Finished release [optimized] target(s) in 5m 23s\n\nCompilation report saved to target/cargo-timings/cargo-timing-20260208T153045Z.html\nTop 5 slowest crates:\n  1. llm v0.1.0          - 2m 15s (codegen)\n  2. ndarray v0.15.6     - 45s (codegen)\n  3. tokio v1.35.0       - 38s (codegen units)\n  4. serde v1.0.193      - 25s (metadata)\n  5. syn v2.0.39         - 20s (build script)\n </tool_result> Build took 5m 23s. The main crate (llm) is the bottleneck at 2m 15s. Consider enabling incremental compilation or using cargo check during development. </s>",
    "User: Run clippy with all features. Assistant: <tool_call> name = shell args = cargo clippy --all-features -- -D warnings </tool_call> <tool_result> error: failed to run custom build command for `openssl-sys v0.9.90`\nCaused by:\n  --- stderr\n  thread 'main' panicked at 'Could not find directory of OpenSSL installation',\n </tool_result> <tool_call> name = shell args = sudo apt-get install libssl-dev pkg-config </tool_call> <tool_result> Reading package lists... Done\nUnpacking libssl-dev (3.0.2-0ubuntu1.12) ...\nSetting up libssl-dev (3.0.2-0ubuntu1.12) ... </tool_result> <tool_call> name = shell args = cargo clippy --all-features -- -D warnings </tool_call> <tool_result> Checking llm v0.1.0\n Finished dev [unoptimized + debuginfo] target(s) in 2.34s </tool_result> Build failed due to missing OpenSSL development headers. Installed libssl-dev and pkg-config, then clippy completed successfully. </s>",
    "User: Deploy to production. Assistant: <tool_call> name = shell args = ./deploy.sh production </tool_call> <tool_result> ERROR: Environment variable DEPLOY_KEY not set\nExiting...\n </tool_result> <tool_call> name = shell args = export DEPLOY_KEY=$(cat ~/.deploy_key) && ./deploy.sh production </tool_call> <tool_result> Deploying to production...\nUploading artifacts...\nRestarting services...\nDeployment complete!\n </tool_result> The DEPLOY_KEY environment variable wasn't set. Loaded it from ~/.deploy_key file and deployment succeeded. </s>",
]

with open('data/tool_calling_training_data.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f'Created {len(data)} properly escaped examples')
